# -*- coding: utf-8 -*-
"""Aula_6_exercicio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UR9blkQLGi-PI2GQCChiTYrkknBqiyhS

# Import Pandas and CSVs
"""

import pandas as pd
#input csv files
dim_cliente = pd.read_csv("/content/dim_cliente.csv")
dim_hub = pd.read_csv("/content/dim_hub.csv")
dim_produto = pd.read_csv("/content/dim_produto.csv")
dim_tempo = pd.read_csv("/content/dim_tempo.csv")
fac_venda = pd.read_csv("/content/fato_envios.csv")
#describe() dataframes -> just to check statistics
dim_cliente.describe()
dim_hub.describe()
dim_produto.describe()
dim_tempo.describe()
fac_venda.describe()

"""# Analyse Data Set
- info() dataframes to check data types
"""

dim_cliente.info()
dim_hub.info()
dim_produto.info()
dim_tempo.info()
fac_venda.info()

dim_cliente.head(10)

dim_hub.head(10)

dim_produto.head(10)

dim_tempo.head(10)

fac_venda.head(10)

"""# Exercicio 1
Total quantidade enviada por cada hub

"""

# merge fac_venda e dim_hub de forma a relacionar hub_id e hub_nome
info_hub_produto=pd.merge(fac_venda,dim_hub,how='inner',on='hub_id')
# groupby hub e quantidade, fazendo ja a soma das quantidades
info_total = info_hub_produto.groupby(["hub_id", "hub_nome"])["quantidade"].sum().reset_index().sort_values("quantidade", ascending=False)
info_total.head(10)

"""# Exercicio 2

Qual produto (ou categoria) teve o maior volume total enviado?
"""

# merge dim_produto e fac_venda para relacionar info produto e venda
info_produto_peso=pd.merge(fac_venda,dim_produto, how="inner", on="produto_id")
# calcular o peso total
info_produto_peso['peso_total']= info_produto_peso["peso_medio_kg"]*info_produto_peso["quantidade"]
# groupby produto e peso total
produto_mais_vendido = info_produto_peso.groupby(['produto_id', 'produto', 'categoria'])['peso_total'].sum().reset_index().sort_values("peso_total", ascending=False)
# identificando o valor maximo
produto_mais_vendido.max()

"""# Exercicio 3

Tempo médio de transporte por categoria de produto

"""

# merge fac_venda e dim_produto para relacionar info produto (categoria) e venda (tempo_transporte_h)
product_avg = pd.merge(fac_venda, dim_produto, how="left", on="produto_id")
# groupby produto e categoria, calculando ja o tempo_transporte_h medio
tempo_medio = product_avg.groupby(['produto_id','produto', 'categoria'])['tempo_transporte_h'].mean().reset_index().sort_values('tempo_transporte_h', ascending=False)
tempo_medio.head()

"""# Exercicio 4

Determine quantos envios totais foram feitos para clientes:
- Grossistas
- Retalho
"""

# merge fac_vendas e dim_cliente para relacionar envio_id e cliente_id com tipo_cliente
tipo_cliente=pd.merge(fac_venda, dim_cliente, how="left", on="cliente_id")
# groupby tipo de cliente e envio_id, calculando já o numero de envios
envios_cliente= tipo_cliente.groupby("tipo_cliente")["envio_id"].count().reset_index().sort_values('envio_id', ascending=False)
envios_cliente.head()

"""# Exercicio 5

Encontre o hub cuja média de tempo de transporte é mais alta.
Mostre o nome do hub e o valor.
"""

# merge fac_venda e dim_hub para relacionar info hub (nome) e venda (tempo_transporte_h)
tempo_hub=pd.merge(fac_venda,dim_hub, how="left", on="hub_id")
# groupby produto e categoria, calculando ja o tempo_transporte_h medio
hub_tempo_medio= tempo_hub.groupby('hub_nome')['tempo_transporte_h'].mean().reset_index()
# identificando o valor maximo
hub_tempo_medio.max()

"""# Exercicio 6

Realize três merges entre fato_envios e dim_cliente usando:
- how="inner"
- how="left"
- how="outer"

____________________________________________________________


Apesar das diferentes parametros de merge how, as tabelas ficam iguais no conteudo de informação que agregam.
- inner apresenta os dados comuns entre as tabelas que estamos a juntar
- left apresenta a primeira tabela completa mais o que existe em comum com a segunda tabela, eliminando o que não é não é comum da segunda
- outer é a reunião das duas tabelas (todas as combinações).
"""

# merge usando how='inner'
merge=pd.merge(fac_venda, dim_cliente, how='inner', on='cliente_id')
merge.head(10)

# merge usando how='left'
merge2=pd.merge(fac_venda, dim_cliente, how='left', on='cliente_id')
merge2.head(10)

# merge usando how='outer'
merge3=pd.merge(fac_venda, dim_cliente, how='outer', on='cliente_id')
merge3.head(10)

"""# Exercicio 7

Após unir as tabelas necessárias, calcule quantidade total enviada por região
"""

# merge fac_venda e dim_cliente para relacionar info hub (regiao) e venda (quantidade)
info_regiao=pd.merge(fac_venda, dim_cliente, how='left', on='cliente_id')
info_regiao.head()
# groupby produto e categoria, calculando ja o tempo_transporte_h medio
quantidade_regiao=info_regiao.groupby('regiao')['quantidade'].sum().reset_index().sort_values("quantidade", ascending=False)
quantidade_regiao.head()

"""# Exercicio 8 - Capacidade vs Uso dos Hubs

Para cada hub:
- obtenha sua capacidade diária
- calcule o volume total enviado
- crie uma coluna percentual_utilizado = volume / capacidade * 100

Mostre quais hubs estão acima de 50% de utilização.
"""

# merge dim_produto e fac_venda para relacionar info produto e venda
info_produto_peso=pd.merge(fac_venda,dim_produto, how="inner", on="produto_id")
# calcular o peso total
info_produto_peso['peso_total']= info_produto_peso["peso_medio_kg"]*info_produto_peso["quantidade"]
# merge info_produto_peso - dim_hub para relacionar info fac_vendas e dim_produto com dim_hub
hub_capacidade=pd.merge(info_produto_peso,dim_hub, how='inner', on='hub_id')
# aggregate only relevant keys and calculate sum 'peso_total'
hub_cap_group=hub_capacidade.groupby(['hub_id','hub_nome','capacidade_diaria','data_id'])['peso_total'].sum().reset_index()
# calculate and add 'percentual_utilizado'
hub_cap_group['percentual_utilizado']=((hub_cap_group['peso_total']/hub_cap_group['capacidade_diaria'])*100).round(2)
# showcase only Hubs with percentual_utilizado over 50%
hub_cap_50=hub_cap_group[hub_cap_group['percentual_utilizado']>50].sort_values('percentual_utilizado', ascending=False)
hub_cap_50.head()

"""# Exercicio 9 - Produto Mais Enviado por Região

Para cada região - Sul, Norte, Centro

Determine qual categoria de produto é mais enviada em volume.
"""

# merge info_produto_peso (variable ex2) and dim_cliente
cliente_peso=pd.merge(info_produto_peso, dim_cliente, how='inner', on='cliente_id')
# groupby 'regiao', 'categoria' and 'peso_total'
regiao_cat_peso=cliente_peso.groupby(['regiao','categoria'])['peso_total'].sum().reset_index()
# identify max
max=regiao_cat_peso.groupby(['regiao'])['peso_total'].idxmax()
# showcase only max
cat_max=regiao_cat_peso.loc[max]
cat_max.head()

"""# Exercicio 10 - Dia com Maior Movimento Logístico

Usando a dimensão tempo, descubra qual data teve o maior total de envios (quantidade).
"""

# merge fac_venda and dim_tempo to relate data_id
data_quantidade=pd.merge(fac_venda, dim_tempo, how='inner', on='data_id')
# aggregate 'data' and sum of 'quantidade'
data_quantidade=data_quantidade.groupby('data')['quantidade'].sum().reset_index()
# identificando o valor maximo
data_quantidade.max()